### ISSUE TITLE
Mask for anime

### ISSUE THREAD

**Issue by SangenBR** [Asd-g/AviSynth-vsTEdgeMask#1]
Hello, I see that you bring some vapoursynth mask for avisynth, would it be possible to bring some specific for anime (for denoise)?

**Comment by Asd-g** [comment]
Hi,
What are more specific for anime masks?

**Comment by SangenBR** [comment]
something like AnimeMask2 that has on vs to get more edges

**Comment by Asd-g** [comment]
AnimeMask/AnimeMask2 port [here](https://github.com/Asd-g/AviSynthPlus-Scripts).

**Comment by SangenBR** [comment]
Oh, Very Thanks.
